version: "3"

services:

  chatgpu-playground-service:
    image: chatgpu-playground:0.0.1
    container_name: chatgpu-playground-service
    build:
      dockerfile: Dockerfile
    environment:
      - chatgpt_email=""
      - chatgpt_password=""
      - chatgpt_paid=false
    ports:
      - "8081:8080"
    volumes:
      - ./app:/app
    tty: true
